const common = [
  require("../images/bonus.svg"),
  require("../images/bonus-display.svg"),
  require("../images/bonus-negative.svg"),
  require("../images/checkbox-off.svg"),
  require("../images/checkbox-on.svg"),
  require("../images/finish-plate.png"),
  require("../images/score-pie.svg"),
  require("../images/snow-small.png"),
  require("../images/splash.svg"),
  require("../images/x.svg"),
];

const resources = {
  1: [
    ...common,
    require("../images/game1/bg.jpg"),
    require("../images/game1/bg-common.jpg"),
    require("../images/game1/bg-common-mob.jpg"),
    require("../images/game1/bg-mob.jpg"),
    require("../images/game1/instruction.png"),
    require("../images/game1/logo.png"),
    require("../images/game1/title-bg.svg"),
    require("../images/game1/title-item.svg"),
    require("../images/game1/objects/bad/o1.png"),
    require("../images/game1/objects/bad/o10.png"),
    require("../images/game1/objects/bad/o11.png"),
    require("../images/game1/objects/bad/o12.png"),
    require("../images/game1/objects/bad/o2.png"),
    require("../images/game1/objects/bad/o3.png"),
    require("../images/game1/objects/bad/o4.png"),
    require("../images/game1/objects/bad/o5.png"),
    require("../images/game1/objects/bad/o6.png"),
    require("../images/game1/objects/bad/o7.png"),
    require("../images/game1/objects/bad/o8.png"),
    require("../images/game1/objects/bad/o9.png"),
    require("../images/game1/objects/good/o1.png"),
    require("../images/game1/objects/good/o10.png"),
    require("../images/game1/objects/good/o11.png"),
    require("../images/game1/objects/good/o12.png"),
    require("../images/game1/objects/good/o2.png"),
    require("../images/game1/objects/good/o3.png"),
    require("../images/game1/objects/good/o4.png"),
    require("../images/game1/objects/good/o5.png"),
    require("../images/game1/objects/good/o6.png"),
    require("../images/game1/objects/good/o7.png"),
    require("../images/game1/objects/good/o8.png"),
    require("../images/game1/objects/good/o9.png"),
  ],
  2: [
    ...common,
    // require("../images/game2/bg.jpg"),
  ],
  3: [
    ...common,
    // require("../images/game3/bg-game.jpg"),
  ],
  4: [
    ...common,
    // require("../images/game4/back-snowflake.png"),
  ],
};

export default resources;
